// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycddmqxizbepkiqydifu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljZGRtcXhpemJlcGtpcXlkaWZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MDY1ODEsImV4cCI6MjA1NzI4MjU4MX0.FT5T6L8gEVVxeS3pmWMLO8LlPzX7OmnjJRl-tj4irfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);